# Generated by Django 5.1.6 on 2025-03-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
